M48
; DRILL file {KiCad (7.0.0)} date Sun Apr 23 17:01:30 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-23T17:01:30-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X145.21Y-105.995
X150.99Y-105.995
T2
X136.0Y-64.0
X136.0Y-110.0
X136.1Y-87.8
X144.9Y-87.8
X168.0Y-64.0
X168.0Y-110.0
T0
M30
